## Java
javax:
  persistence:
    schema-generation:
      scripts:
        action: drop-and-create

## Spring Config
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  ## JPA Config
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

## ContextPath Config
server:
  servlet:
    context-path: /api/v1

## Database config
datasource:
  jdbc-url: "jdbc:mysql://127.0.0.1:3306/store"
  username: "root"
  password: "1234"

## logging
logging:
  level:
    com:
      example:
        app: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace