## Spring Config
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  ## JPA Config
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

## ContextPath Config
server:
  servlet:
    context-path: /api/v1

## Database config
datasource:
  master:
    initialize: true
    jdbc-url: "jdbc:mysql://127.0.0.1:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: "root"
    password: "1234"
  slave:
    initialize: true
    jdbc-url: "jdbc:mysql://127.0.0.1:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: "root"
    password: "1234"

## logging
logging:
  level:
    root: info
    com:
      example:
        app: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace